---
- name: create the deployments and services for jenkins
  command:  kubectl apply -f -
  args:
      stdin: "{{ lookup('template', '{{ item }}-jenkins.yaml.j2') }}"
  loop:
    - deployment
    - service       
# tasks file for jenkins
